### ISSUE TITLE
Click on sent-message dot does not work

### ISSUE THREAD

**Issue by r2evans** [threadvis/ThreadVis#1]
Double-clicking on received (filled) circles creates a new tab showing the clicked email, as expected.

Double-clicking on sent (hollow) circles creates a new tab with an empty tab name and shows the same email as the tab in which I double-clicked. It does not show the sent email, as expected. (Other than the lack of a tab title, it is identical to the previous tab.)

Win7-64, TB 24.1.0, ThreadVis 2.2.0

**Comment by ahubmann** [comment]
Sorry for the late reply, I'll try to find a solution and/or better logging to see what the actual problem is. Does ThreadVis display the message preview if you hover over the sent message?

**Comment by zuzullo** [comment]
Hi
Yes it does, but not when we click on it. When we click on it, nothing happens. Please advise. We used threadvis before and it was working very nice.

Kind regardsZuzullo

Date: Tue, 27 Jan 2015 02:21:44 -0800

**Comment by mskorzhinskiy** [comment]
Hello. The issue still reproduce on the thunderbird 52.1.0 and ThreadVis 2.2.0.
Also, I've tried to move some other message (i.e. not from me) to other folder. The behaviour is the same. So the current synopsis is the following:
After double-clicking the message that is not from the current folder, the "empty" tab is opening. Albeit, after hovering to the messages that is not from current folder, they are displaying without any issues.

**Comment by mskorzhinskiy** [comment]
I'm REALLY not sure what happened, since the last commit was 4 yeas ago, but the issue just disappear. The only thing that I do is update thunderbird and change 'mail.server.default.check_all_folders_for_new' to the TRUE.
