### ISSUE TITLE
"Loading ThreadVis" error with TB 31.2

### ISSUE THREAD

**Issue by orschiro** [threadvis/ThreadVis#11]
Hi @ahubmann 

Thanks a lot for developing ThreadVis!

I was looking for a simple thread view and decided that ThreadVis suits my needs better than Thunderbird Conversations. 

However, the actual thread visualisation is not shown in Thunderbird 31.2:

![screenshot](https://cloud.githubusercontent.com/assets/170947/4751570/a94ce4a4-5a9f-11e4-8ff7-2ae64c2d7bf8.png)

Do you have any advice for me how to make it compatible?

Thank you very much!

```
thunderbird 31.2.0-1
Arch Linux 64-Bit
```

**Comment by codemeleon** [comment]
Hi, 

I am having the same Issue with Thunderbird 78.4.3 . I reinstalled the plugin again. However, it didn't solve the issue. 

Thanks.
