### ISSUE TITLE
This is a missing message error

### ISSUE THREAD

**Issue by orschiro** [threadvis/ThreadVis#14]
Hi,

I face the issue that ThreadVis is telling me that a related message is missing although the entire conversation thread is present (although not in the same folder). For instance, the same message is properly displayed as a conversation thread in the Gmail interface.

![screenshot](https://cloud.githubusercontent.com/assets/170947/5025453/6b728f78-6b19-11e4-8569-3d32f3e42673.png)

Could you tell me why this is happening and whether something can be done about it?

Thanks!

**Comment by ahubmann** [comment]
Hm. So the message is in a different folder in the same account? And all folders are synced locally and indexed by Thunderbird? The error stems from the fact that the second email contains either a "References" or "In-Reply-To" header which references a message-id which ThreadVis could not look up in the message database. Hard to debug, but I'll see what I can do.

**Comment by orschiro** [comment]
I am not very actively using threadvis anymore. So please don't put too
much work into it if I am the only person affected.

Robert

Lazy type mode on from mobile

**Comment by marmistrz** [comment]
You have to enable syncing the Sent folder.

The problem is that if an unread message would be in two synced folders, it'd appear twice in the Thunderbird notifications.
