### ISSUE TITLE
Wobbling header 

### ISSUE THREAD

**Issue by cburlacu** [threadvis/ThreadVis#19]
Hi,

I have this issue. I am registered to linux kernel mailing list and for those emails with a lot of patches and replies, when you select those emails it starts to wobble and becomes almost impossible to be able to read the emails.
[issue.ogv.zip](https://github.com/threadvis/ThreadVis/files/108478/issue.ogv.zip)

I uploaded a sample. There are times when it wobbles much faster.

**Comment by mamert** [comment]
Got the same thing, very frequently. From Redmine updates, usually. Always the same speed, though, as far as I can tell.
Anything I can do to help debug?

**Comment by ahubmann** [comment]
Apologies for never following up on this issue. As there's no use in hunting this down in an old version of ThreadVis: are you still seeing this or similar behavior in the current 3.4.2 on Thunderbird 102?
