### ISSUE TITLE
Time difference in Time Scaling inconsistent display

### ISSUE THREAD

**Issue by r2evans** [threadvis/ThreadVis#2]
I do not see the time between emails in the unmodified view. Current configuration:
- Extension enabled
- "Enable Time Scaling"
- Method: linear or logarithmic, same results
- Minimum displayed time difference: automatic or 1 day, no change
- Selected: Display the time between two messages
- Sizes: 10, 10, 10, 2, 2, 16, 10, full, circles (yes)

![image](https://f.cloud.github.com/assets/5815808/1439245/84358a44-4188-11e3-8c8d-9d486326665f.png)

If I expand the view twice (either directly in the message-header display or using the "+" icon in the separate window), only then do I see the time between emails. Unfortunately, I see all of them regardless of the minimum time difference setting. (When minimum="1 day", I expect this to only display text if the difference between any two emails is at least 1 day. The "5h", "42m", etc, should all not be shown.)

![image](https://f.cloud.github.com/assets/5815808/1439254/8fe9bd38-4188-11e3-820c-9a9a8fae62d1.png)

Additionally, not certain if it's a related issue, but the autofit functionality is not quite right. It usually starts out fine when opening a message, but if I change anything such as trying to zoom in on it, it has a limited frame in which it is working, and doesn't rescale it.

![image](https://f.cloud.github.com/assets/5815808/1439298/3c84def6-4189-11e3-9db2-953b2c05f32c.png)

Win7-64, TB 24.1.0, ThreadVis 2.2.0

**Comment by ahubmann** [comment]
Cleaning up older issues, this should be greatly improved in 3.5.1.

If you're still seeing issues with the current release on Thunderbird 115 ("Supernova"), please re-open this issue or create a new one.
