### ISSUE TITLE
Timeline time deltas not rendered

### ISSUE THREAD

**Issue by cpbotha** [threadvis/ThreadVis#21]
In the screenshot on https://addons.mozilla.org/en-US/thunderbird/addon/threadvis/?src=search I see that each email in the ThreadVis has a text label showing how old that mail is.

With Thunderbird 45.5.1 on Ubuntu 16.04 where ThreadVis otherwise seems to be working well, I don't see these time delta labels. (See attached screenshot)

Is this something that I still need to configure, or is it perhaps due to changes made in TB since the last ThreadVis release?

![image](https://cloud.githubusercontent.com/assets/937871/21848670/a4fa522a-d80a-11e6-96b2-0d5788a79d26.png)

**Comment by ahubmann** [comment]
Apologies for never following up on that. If you're still a Thunderbird/ThreadVis user, are you still seeing this issue on Thunderbird 102 with ThreadVis 3.4.2?

**Comment by cpbotha** [comment]
Thank you for following up @ahubmann !

I am sorry, I ended up with Emacs and mu4e :)
