### ISSUE TITLE
stopped working with Thunderbird 58b1

### ISSUE THREAD

**Issue by davidoetiker** [threadvis/ThreadVis#24]
Starting with Thunderbird 58b1 (win32), threadvis 2.2.0 is no more showing up on the message header.
I don't see any message in the errorconsole.

**Comment by ahubmann** [comment]
Thanks for the heads up. Seems the beta versions changed the message header layout (also seeing some strange Javascript errors), which prevent ThreadVis from loading. I'll check the current beta channel and try to release an update before this hits the release channel.

**Comment by ahubmann** [comment]
Fixed two Javascript errors (deprecated interfaces), loading again now. I'll do some more testing to make sure there are no other hidden errors and then release an update.

**Comment by koobs** [comment]
@ahubman Happy to test a (addon) development channel release and report back if you can create one

**Comment by ahubmann** [comment]
I've pushed the relevant changes and uploaded a new version (2.3.0) to Github. Feedback welcome. Direct link: https://github.com/threadvis/ThreadVis/releases/download/2.3.0/ThreadVis-2.3.0.xpi

**Comment by koobs** [comment]
The 2.3.0 update referenced above was working for me with 58.*, but stopped working again with 60.* (beta channel).

@ahubmann Could you update the max version support to include 60.* and produce a new (dev) release. I'm happy to test and report back

**Comment by ahubmann** [comment]
Thanks for notifying me, I've published an updated version (2.3.2), available at https://github.com/threadvis/ThreadVis/releases/download/2.3.2/ThreadVis-2.3.2.xpi and (pending review) also on addons.mozilla.org.

This only pushes the max version to 60.*, I'll look into the issue you described for the next release.
