### ISSUE TITLE
SVG export malformed

### ISSUE THREAD

**Issue by r2evans** [threadvis/ThreadVis#3]
The exported SVG does not match what is visible. For instance, what I see:

![image](https://f.cloud.github.com/assets/5815808/1439335/be2865b8-4189-11e3-8e82-22c78d1ed8bb.png)

What is exported (converted from SVG to PNG because github is not allowing SVG pastes/uploads):

![1-threadvis-nodiff](https://f.cloud.github.com/assets/5815808/1439360/11f672a2-418a-11e3-872f-cc89c3dcc968.png)

Win7-64, TB 24.1.0, ThreadVis 2.2.0

**Comment by ahubmann** [comment]
Cleaning up older issues. SVG export has seen quite a few rewrites meanwhile.

If you're still seeing issues with the current release (3.5.1) on Thunderbird 115 ("Supernova"), please re-open this issue or create a new one.
