### ISSUE TITLE
Thunderbird 64 bits Windows Compatibility

### ISSUE THREAD

**Issue by aliban** [threadvis/ThreadVis#30]
Just tried to use it Thunderbird Windows 64 bits with 60.8.0 version but the plugin it's marked as not compatible.

**Comment by bitwave** [comment]
Same here with Linux.

**Comment by ahubmann** [comment]
Are you sure it's Thunderbird 60.8.0 and not 68.0? I'm working on an update to fix compatibility with Thunderbird 68 (ThreadVis itself is working, still need to fix the settings dialog).

**Comment by aliban** [comment]
Hello

 Sorry my bad 68.0 version on 64 bits Windows

**Comment by ahubmann** [comment]
Please see latest 3.0.0 release [XPI](https://github.com/threadvis/ThreadVis/releases/download/3.0.0/ThreadVis-3.0.0.xpi) for Thunderbird 68 compatibility. Let me know if you see any issues with this version.

Submitting this release for review to AMO as well, should hopefully be online there as well soon.

**Comment by ahubmann** [comment]
Apologies, please use [3.0.1](https://github.com/threadvis/ThreadVis/releases/download/3.0.1/ThreadVis-3.0.1.xpi), I lost a couple of file renames while packing up 3.0.0.

**Comment by aliban** [comment]
Works like a charm, many many many thanks fot the good job. This is a must addon
