### ISSUE TITLE
Thunderbird 68 compatibility

### ISSUE THREAD

**Issue by MayeulC** [threadvis/ThreadVis#31]
You never realize how much you use something until it stops working.

I feel like my thunderbird client is crippled since it was updated to the latest version, a few weeks ago. Since I have not seen it discussed, are there plans to bring ThreadVis to this new version?

**Comment by ahubmann** [comment]
Yes, working on it. Most things are working already in Thunderbird 68, still need to rework the settings dialog. Expect an updated version within a week or two (hopefully).

**Comment by ahubmann** [comment]
Please see latest 3.0.0 release [XPI](https://github.com/threadvis/ThreadVis/releases/download/3.0.0/ThreadVis-3.0.0.xpi) for Thunderbird 68+. Let me know if you see any regressions...

**Comment by aliban** [comment]
Thunderbird 68.1.1 64-bit on Windows 10 only got message Loading ThreadVis

**Comment by ahubmann** [comment]
Apologies, somehow I lost a couple of file renames in publishing this update. Fixed in [3.0.1](https://github.com/threadvis/ThreadVis/releases/download/3.0.1/ThreadVis-3.0.1.xpi).

**Comment by aliban** [comment]
Fixed, many thanks

**Comment by MayeulC** [comment]
Hmm, Thunderbird tell me this add-on (v3.0.1, md5: `28846d45c44dda02f38b582a17d278c0`, but same on 3.0.0) is incompatible with it (version 68.1.1). I am running the Thunderbird version from Arch Linux packages. Is there anything else I should do?

**Comment by ahubmann** [comment]
Oh wow, sorry about never following up on that last comment. Guess I'll close this now after 3 years. There's 3.4.2 now available for Thunderbird 102.
