### ISSUE TITLE
coding problem viewing emails

### ISSUE THREAD

**Issue by grac-zh** [threadvis/ThreadVis#33]
when activating a new reply in the timeline of threadvis to show in thunderbird, the coding is incorrect (conflict between ANSI/ASCII and UTF-8: german umlauts).

after having opened the reply through thunderbird directly, threadvis afterwords shows also correct coding.

**Comment by jrathlev** [comment]
The same issue applies to me:
Thunderbird 78.6.1
ThreadVis 3.1.1

**Comment by Beexx** [comment]
Same issue for me. Not new : this behaviour has always been the same. This is very annoying. 
TB 78.13 , ThreadVis 3.1.1. 

To summarize :
- the first time a mail is opened by clicking on a dot in the Threadvis pane, the display is incorrect (wrong character encoding : UTF8 is not used for accentuated characters)
- the second time the mail is opened (after switching to another mail), either by clicking directly in TB message list, or by clicking again on the Threadvis dot, the correct encoding is applied and the message can be read.

Solving this would be really appreciated by all German, Spanish, French users... Thanks !

**Comment by ahubmann** [comment]
Sorry for never following up on this: I haven't been able to reproduce this issue on the newer Thunderbird versions (seen it before as well). Would be glad to hear back if that's still an issue in Thunderbird 102 / ThreadVis 3.4.2.

**Comment by grac-zh** [comment]
hi there

no, it's gone!
and thanks for updating your wonderful addon, I missed it very much!

grac

**Comment by ahubmann** [comment]
Many thanks for the quick reply. Closing this issue as "somehow resolved by Thunderbird", feel free to reopen or create a new issue should you run into this again.
