### ISSUE TITLE
Doesn't show the thread oin 78.1.1

### ISSUE THREAD

**Issue by jmsende** [threadvis/ThreadVis#34]
The plugin doesn't comply about compatibility but doesn't work on Thunderbird 78.1.1
The issue presents on Windows 10 64 bit version of Windows Thunderbird with dark theme selected

**Comment by currificado** [comment]
Same here. I find this plugin extremely useful so I had to downgrade Thunderbird by the moment. I hope ThreadVis is updated soon. Thanks.

**Comment by ahubmann** [comment]
Working on it. Basic functionality is already working in Thunderbird 78, preferences/settings need a major rewrite. I'll try to get an initial version out soon.

**Comment by jmsende** [comment]
If you need a beta tester I will gladly will do it

**Comment by RickardSvard** [comment]
Hello Juan, I have test the latest version but it don't work, see the 
picture.

ThV: 3.0.1
TB: 78.2.2
Windows 7 sp1 64bit

//Rickard/
+4670 575 01 84
IT Consult Rickard Svärd 
<https://itcrs.se/rickard_svard/?utm_source=Email&utm_medium=link&utm_campaign=Signature>
------------------------------------------------------------------------

**Comment by ahubmann** [comment]
Almost done, settings dialog working, most glaring missing features re-implemented. I'll do some more testing over the weekend and can hopefully release 3.1.0 for Thunderbird 78 next week. Thanks for your patience!

**Comment by ahubmann** [comment]
I've pushed version 3.1.0 to GitHub (see https://github.com/threadvis/ThreadVis/releases/tag/3.1.0). Working on getting this version submitted to Thunderbird Add-Ons, but it seems the Linter there doesn't like my code the same way I do ... ;-)

So expect another 3.1.1 release for syntax changes to submit to the Thunderbird Add-On repository.

**Comment by hagedose** [comment]
I'm a new user, because I only learned about this Add-On after I had upgraded to TB 78. I'm on TB 78.3.2 on macOS. I was able to install 3.1.0.86a87b8.1602055697, I can see its settings, the icon is in the lower right, but nothing else seems to happen. I have confirmed that all accounts and folders are activated in ThV's settings. Is there anything else I need to do?

**Comment by ahubmann** [comment]
That's certainly weird. I'm on 78.3.2 on macOS as well, I completely removed the add-on, restarted Thunderbird, installed it again and it works as intended.

* So there's no display of the thread in the header of the e-mail?
* Do you have any other add-ons installed that are changing the message header display?
* Can you check the error console (Tools / Developer)?

**Comment by hagedose** [comment]
> That's certainly weird. I'm on 78.3.2 on macOS as well, I completely removed the add-on, restarted Thunderbird, installed it again and it works as intended.
> 
> * So there's no display of the thread in the header of the e-mail?

Exactly.

> * Do you have any other add-ons installed that are changing the message header display?

Yes, DKIM Verifier 4.0.0pre2. But I deactivated that, and it didn't make any difference. I have a few other add-ons, but none that change the message header display, AFAIK.

> * Can you check the error console (Tools / Developer)?

I should've mentioned that I already did that. I can't see any trace of ThreadVis there.

**Comment by ahubmann** [comment]
Version 3.1.1 is now available with minor code-linting changes to pass the upload checks on Thunderbird Add-Ons, see https://github.com/threadvis/ThreadVis/releases/tag/3.1.1 (This version has now also been submitted for review and should appear on Thunderbird Add-Ons if there are no changes required by the reviewer(s).)

**Comment by ahubmann** [comment]
@hagedose thanks for the swift reply, that behaviour is certainly weird. The icon in the lower right shows as coloured?

On a long shot: you haven't by chance disabled the global search index in Thunderbird? ThreadVis relies on the data stored there.

**Comment by hagedose** [comment]
The global search index is active. The icon in the lower right looks like this:

<img width="92" alt="Bildschirmfoto 2020-10-07 um 10 50 50" src="https://user-images.githubusercontent.com/1461803/95309195-1e7e4480-088b-11eb-997f-e05b8a93d946.png">

I have upgrade to version 3.1.1, btw.

**Comment by ahubmann** [comment]
Any details show in the context menu if you click on it? (I assume it should say "Enabled" for all items, as it's displayed in colour. Otherwise it would show up as grey...)

Your e-mail headers are not by chance collapsed? (I'm wildly guessing here, as there are no errors shown... I might create a debug version with some added logging to the error console, if you're willing to invest time to debug this.)

![Bildschirmfoto 2020-10-07 um 10 55 24](https://user-images.githubusercontent.com/5640706/95309875-fb07c980-088b-11eb-8fa6-4b696bbf35b1.png)

**Comment by hagedose** [comment]
I would gladly test a debug version. This is what I'm seeing:

<img width="198" alt="Bildschirmfoto 2020-10-07 um 10 59 18" src="https://user-images.githubusercontent.com/1461803/95310065-3b674780-088c-11eb-91d6-a47b511bad28.png">

<img width="1571" alt="Bildschirmfoto 2020-10-07 um 11 00 47" src="https://user-images.githubusercontent.com/1461803/95310183-62257e00-088c-11eb-8e02-afc2cd5353b6.png">

**Comment by RickardSvard** [comment]
It works fine for me now!
ThV: 3.1.1
TB: 78.2.1
Nice work.
/Rickard

**Comment by lenhodder** [comment]
@ahubmann Thank you for updating!  Looking great so far on TB v78.3.1.
Cheers.
Len

**Comment by jmsende** [comment]
Works great! Many thanks

**Comment by hagedose** [comment]
> Works great! Many thanks

I'm glad it works for you, but it doesn't yet for me ...

**Comment by ahubmann** [comment]
Ah, wrong button. I wanted to re-open this one.

**Comment by ahubmann** [comment]
Unsure if I ever followed up on this. I guess not, I'm really sorry about that. If you're still a Thunderbird user, there's now 3.4.2 for Thunderbird 102. Would be glad to hear back if it's working again for you. Otherwise I'd follow up on this for real this time, promise!

**Comment by ahubmann** [comment]
Cleaning up older issues, apologies for (again) not following up.

If you haven't given up on Thunderbird/ThreadVis completely, and if you're still seeing issues with the current release (3.5.1) on Thunderbird 115 ("Supernova"), please re-open this issue or create a new one.
