### ISSUE TITLE
can’t move to other message in a thread

### ISSUE THREAD

**Issue by sebalis** [threadvis/ThreadVis#36]
As an followup to issue #35, one thing that does not work regardless of whether a message is displayed in a tab or in conversation view: The circles for the other messages in the ThreadVis display still act as though they are clickable (i.e. the mouse pointer changes) but when I click on them, nothing happens. This used to open the message whose circle I’ve clicked in the same tab (or, pre-68, message window). Again, it would be very nice if this could reinstated. Thanks for your work anyway.

**Comment by ahubmann** [comment]
Cleaning up older issues, apologies for the complete non-reply to your issue.

If you're still seeing issues with the current release (3.5.1) on Thunderbird 115 ("Supernova"), please re-open this issue or create a new one.

**Comment by sebalis** [comment]
I had deactivated ThreadVis for a while. Now I notice that the issues I reported are indeed resolved. Thank you so much, also for making me aware of it!
