### ISSUE TITLE
Time between messages not shown

### ISSUE THREAD

**Issue by antotamtam** [threadvis/ThreadVis#38]
Just installed 3.1.1 release for TB 78.4.1, and I see that time difference between messages is missing. Of course I checked settings are configured to be displayed, and tried to uncheck and re-check to no avail.

**Comment by antotamtam** [comment]
Nobody else is able to reproduce this issue? I uninstalled Threadvis and installed it again, rebuild the global database... timeline is still missing. Any help would be pretty much appreciated!

**Comment by ahubmann** [comment]
Picking up old issue threads: are you still seeing this behavior on 3.4.2 (Thunderbird 102)? At least for me with "full (no zoom)" display of the time difference is working.

**Comment by ahubmann** [comment]
Display of timeline should be greatly improved meanwhile in 3.5.1. Closing. Please re-open or create a new issue if needed!
