### ISSUE TITLE
thread view

### ISSUE THREAD

**Issue by mlana** [threadvis/ThreadVis#39]
hi, 
for threads with many messages the threadvis "fit" visualizations gives -understandably - a very small image of the thread when the message is showed in the global view folders/threads/message, where the message view is quite compressed (see image threadvis1)
but the image of the thread remains very small also when the message is open in full screen mode (see image threadvis2) and the available space for threadvis grows. one would expect that if the available space grows the "fit" visualization enlarges itself.
best
maurizio
<img width="1436" alt="threadvis1" src="https://user-images.githubusercontent.com/4612795/99854001-4a782f80-2b84-11eb-88f3-2d0c7c88e563.png">
<img width="1163" alt="threadvis2" src="https://user-images.githubusercontent.com/4612795/99854013-5106a700-2b84-11eb-9f0b-7bd2ff25cf7b.png">

**Comment by ahubmann** [comment]
Picking up old unresolved issues: I'll check what's going on here.

It seems the previous scaling is not updated when the visualization is rendered in a new tab, hence it's not using the available space at all.

Thanks for reporting, even if I'm 2 years late by now.

**Comment by ahubmann** [comment]
This should actually be fixed by now in 3.5.1, if not, please re-open this issue!
