### ISSUE TITLE
Request: option to open in same tab

### ISSUE THREAD

**Issue by r2evans** [threadvis/ThreadVis#4]
The current default when double-clicking on a circle is to open the target email in a new tab. Is it possible instead to open it into the current tab, replacing the current tab's previous contents with the intended email?

Win7, TB 24.1.0, ThreadVis 2.2.0

**Comment by ahubmann** [comment]
Current release (3.5.1) allows for navigating in separate tabs, single click stays in the same tab, double click opens in a new tab. Closing.
