### ISSUE TITLE
Show/Hide the statusbar button

### ISSUE THREAD

**Issue by sphh** [threadvis/ThreadVis#41]
Thanks for this beautiful and useful add-on!!

`ThreadVis` shows a button in the statusbar, which is never used (at least not by me), because after setting up the configuration once in the `Preference` page I see no need to switch it on or off or have a quick access to change the settings.

Is there a way to not show this button, because it uses up valuable space in the statusbar? I rather would like to use the space for the [Manage emails / Nostalgy++](https://addons.thunderbird.net/en-GB/thunderbird/addon/nostalgy_ng/) add-on than for a functionality which I don't use (that is the button, not the `ThreadVis` add-on)? Obviously the very best option would be to add a configuration option to show/hide this button …

**Comment by ahubmann** [comment]
Interesting idea. Never thought about an option to hide the statusbar button, as 80% of my personal statusbar is empty and unused and space isn't an issue. Shouldn't be too hard to add ...

**Comment by sphh** [comment]
I forgot to mention, that the [Send later](https://github.com/Extended-Thunder/send-later/) has this feature already implemented …

**Comment by ahubmann** [comment]
Functionality to hide the status bar icon was actually already added as part of 3.5.0.

**Comment by sphh** [comment]
Thanks for adding this feature a while back.
