### ISSUE TITLE
Thunderbird 91.xx supported? Doesn't work on my installation

### ISSUE THREAD

**Issue by domosbg** [threadvis/ThreadVis#44]
Hello,
should ThreadVis actually work on Thunderbird 91.x? I tried it on a few installations and it seems not to work. The message tree is not shown in the mail header:
![grafik](https://user-images.githubusercontent.com/88573684/131966038-7823e31f-43d2-4f89-a782-21ebe68c0de1.png)

Besides the Threadvis Label in the lower right corner of Thunderbird is not shown and the preferences of the addon are not shown in the preferences dialog:
![grafik](https://user-images.githubusercontent.com/88573684/131966822-b2a68783-c890-4f17-bfb8-20b1ec3182ce.png)

Can anybody confirm this oder is it a problem with my installations? Also tried to reinstall the add-on. Doesn't help.

It would be really nice if the addon would still work under the new thunderbird versions, because it is one of my favorite addons.

**Comment by LorisAlbanese** [comment]
I confirm that with the latest version of thunderbird it stopped working. Trying to reinstall Th say "it's not compatible".

**Comment by domosbg** [comment]
It's not compatible is shown since version 92.x. In version 91.x there is no incompatibility message but it don't work.

There are messages in the debug windows of thunderbird in v91:
![grafik](https://user-images.githubusercontent.com/88573684/133144974-06125f0e-d268-4e50-bb7f-c7f11fb2bafb.png)

Unfortunately I don't know where this errors come from, because I have no knowledge how the add-on programming is working.

There seems to be changes in the addon programming interface from version 78 to 91:
https://developer.thunderbird.net/add-ons/updating/tb91
https://developer.thunderbird.net/add-ons/updating/tb91/changes

Anybody here who has experience in addon programming who can take a look at it?

**Comment by ahubmann** [comment]
Yes, there've been quite a few changes for legacy add-ons (which are using "experiments" to add functionality not yet available in WebExtensions), but I'm working on an update. It's almost working (tests pending), and I hope I can upload the new version sometime this week.

**Comment by ahubmann** [comment]
3.2.0 has just been released. It's awaiting review on addons.thunderbird.net, but you can manually install it from https://github.com/threadvis/ThreadVis/releases/download/3.2.0/ThreadVis-3.2.0.xpi already.

**Comment by domosbg** [comment]
Great. Thank you very, very much for keeping the addon up to date.

I try to install it in the beta version 93.x, but Thunderbird says it is not compatible. Is it only because in the manifest there is a max version 91.x defined or is it neccessary to make further changes for the newest beta versions? If not, it would be nice if the max version in the manifest file could be changed to the latest beta versions.

**Comment by ahubmann** [comment]
I haven't tested it with Thunderbird 93, but I assume it's "just" limited by the max version in the manifest (which is now a required field, previous versions were unbound). I'll give it a spin with 93 and if there are no obvious errors, I'll push another small update to bump the max version.

**Comment by ahubmann** [comment]
Seems no implementation changes are necessary for 93, so here's 3.2.1, supporting Thunderbird 91 and 93: https://github.com/threadvis/ThreadVis/releases/download/3.2.1/ThreadVis-3.2.1.xpi

**Comment by domosbg** [comment]
![grafik](https://user-images.githubusercontent.com/88573684/133751695-931407ac-0d43-46ee-9c5c-70313bc1b37e.png)

Yeah, It's working again... thanks a lot again.
