### ISSUE TITLE
From TB 91 and v3.3.0 don't see anything in messages

### ISSUE THREAD

**Issue by Fabick75** [threadvis/ThreadVis#46]
I've the latest version of plugin installed, under TB v91.7.0 and Fedora 36. I've tested on Ubuntu too: the plugin don't give me anything.
Opening the console ( with CTRL + SHIFT + I ), I found this error :+1: 

```
TypeError: this.stack is null[visualisation.jsm:391:9](chrome://threadvis/content/visualisation.jsm)
    displayDisabled chrome://threadvis/content/visualisation.jsm:391
    setSelectedMessage chrome://threadvis/content/threadvis.jsm:438
    observe chrome://threadvis/content/threadvis.jsm:157
    OnMsgParsed chrome://messenger/content/mailWindowOverlay.js:3736
    onEndMsgDownload chrome://messenger/content/msgHdrView.js:840
```
Opening the link of "visualization.jsm" I found this in line 391 : 
` this.stack.appendChild(warning);`

seems that some variable or some method was not populated (or existent).

Could you verify this problem?

**Comment by ahubmann** [comment]
Apologies for the _very late_ reply. Are you still seeing this error in the current Thunderbird version 102 and ThreadVis 3.4.2?

Error seems to indicate that the `this.stack` variable was not set (it's pointing to a UI element) prior to the code displaying the warning being called. In theory, this should not happen, you obviously found a counter-example.

**Comment by grrrrr** [comment]
@ahubmann   not op but I see the same issue.   Visually there is no sign of ThreadViz "thread" when you open an email.

**OS:** Fedora 38
**Email:**  Thunderbird 102.12.0 (64-bit)
**Add-On:** ThreadVis 3.4.2 / Allow HTML Temp 8.1.5 / Provider for Google Calendar 102.0.3 (disabled)
**Encryption:** OpenPGP

In console

```
Uncaught TypeError: this.stack is null
    displayDisabled chrome://threadvis/content/visualisation.jsm:366
    setSelectedMessage chrome://threadvis/content/threadvis.jsm:446
    onEndHeaders chrome://threadvis/content/threadvis.jsm:148
    onEndHeaders chrome://messenger/content/msgHdrView.js:566
    processHeaders chrome://messenger/content/msgHdrView.js:713
visualisation.jsm:366:9
    displayDisabled chrome://threadvis/content/visualisation.jsm:366
    setSelectedMessage chrome://threadvis/content/threadvis.jsm:446
    onEndHeaders chrome://threadvis/content/threadvis.jsm:148
    onEndHeaders chrome://messenger/content/msgHdrView.js:566
    processHeaders chrome://messenger/content/msgHdrView.js:713
```

**Comment by ahubmann** [comment]
Cleaning up older issues, apologies for not following up further.

If you're still seeing issues with the current release (3.5.1) on Thunderbird 115 ("Supernova"), please re-open this issue or create a new one.
