### ISSUE TITLE
Plugin version 3.4.2 not working with Thunderbird 102.5.1

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [threadvis/ThreadVis#49]
I just heard about the plugin and installed version 3.4.2 with Thunderbird 102.5.1 on Windows 11.
By seeing the debugger console I get this error every time I click on a message: `Message not found in Gloda.`

**Comment by ahubmann** [comment]
Cleaning up older issues, apologies for the complete non-reply to your issue.

If you're still seeing issues with the current release (3.5.1) on Thunderbird 115 ("Supernova"), please re-open this issue or create a new one.
