### ISSUE TITLE
Right-click context menu has no background

### ISSUE THREAD

**Issue by r2evans** [threadvis/ThreadVis#5]
When I right-click on the thread view to get the menu, there is no background, so it is annoying to read the options, especially if it overlaps with any of the email message itself (no email text shown in this example).

![image](https://f.cloud.github.com/assets/5815808/1439408/e3627a98-418a-11e3-9e55-e5ab0348927d.png)

Win7, TB 24.1.0, ThreadVis 2.2.0

**Comment by ahubmann** [comment]
Following up on old issues: I think there's no use in still checking this after 8 years. If you're still seeing this with a current Thunderbird 102 / ThreadVis 3.4.2, please re-open.
