### ISSUE TITLE
TreadVis grayed out on TB 115.9.0

### ISSUE THREAD

**Issue by moedn** [threadvis/ThreadVis#56]
Hey there! First of all: Thousand thanks for your work! I really love ThreadVis and since I'm dealing with large, messy mail threads on a regular basis it became an indispensable asset for my work – in fact it was one of the reasons why I wouldn't leave TB.

However, since a while it's not showing up anymore. This was an issue in the past as well, after TB updates, but this time the waiting became concerningly long :)

I'm not quite sure though how to troubleshoot this; please let me know if there's a way how to export helpful logs.

ThreadVis is enabled in the Addon-Manager…

![image](https://github.com/threadvis/ThreadVis/assets/45949491/d4252160-e8fe-4e77-b090-f852b78fd56e)

…but not showing up in the header and grayed out in the bottom bar

![image](https://github.com/threadvis/ThreadVis/assets/45949491/31154961-8c18-44f0-9f94-3fd8a114fca3)

**System Specs:** Fedora 39; kernel `6.7.9-200.fc39.x86_64`

**Comment by ahubmann** [comment]
Ok, this is weird. Can you check the error console (via _Tools_) to see if there are any errors logged?

I'm running Thunderbird 115.9.0 on macOS with a slightly newer version of the add-on, but the changes do not affect loading and general display - and I'm seeing absolutely no issues.

**Comment by moedn** [comment]
Thanks for the blazingly help!

here's a screenshot from the log (+ raw text below) from launching thunderbird and trying to open ThreadVis. can't really see much in there, but maybe you'll find something :)

![Screenshot from 2024-03-28 17-53-11](https://github.com/threadvis/ThreadVis/assets/45949491/41d106fd-5374-487d-9eb3-f71401df6210)

```
1711644677849	addons.xpi	WARN	Checking /usr/lib64/thunderbird/distribution/extensions for addons
1711644679058	addons.xpi	WARN	Addon with ID thunderbird-compact-light@mozilla.org already installed, older version will be disabled
1711644679059	addons.xpi	WARN	Addon with ID thunderbird-compact-dark@mozilla.org already installed, older version will be disabled
Found 19 public keys and 10 secret keys (10 protected, 0 unprotected) [RNPLib.jsm:559:15](chrome://openpgp/content/modules/RNPLib.jsm)
Uncaught ReferenceError: module is not defined
    <anonymous> moz-extension://5daa8ed6-f2fb-45fe-8506-94fc6840bd8f/punycode/punycode.js:440
[punycode.js:440:1](moz-extension://5daa8ed6-f2fb-45fe-8506-94fc6840bd8f/punycode/punycode.js)
    <anonymous> moz-extension://5daa8ed6-f2fb-45fe-8506-94fc6840bd8f/punycode/punycode.js:440
initExtension() [background.js:86:16](moz-extension://ed78aed1-795b-4a58-bbbf-6e5f2a10052b/scripts/background.js)
unreachable code after return statement
[QNoteFilter.js:69:2](resource://qnote/modules/QNoteFilter.js)
WebExtensions: new qapp() [qapp.js:19](jar:file:///home/ruediger/.thunderbird/i4bitooi.default-release/extensions/qnote@dqdp.net.xpi!/api/qapp.js)
initCurrentNote(setUpExtension) [background.js:22:16](moz-extension://ed78aed1-795b-4a58-bbbf-6e5f2a10052b/scripts/background.js)
Missing resource in locale en-GB: devtools/client/toolbox.ftl
Missing resource in locale en-CA: devtools/client/toolbox.ftl
Error: Can't find profile directory. [XULStore.sys.mjs:60:15](resource://gre/modules/XULStore.sys.mjs)
    load resource://gre/modules/XULStore.sys.mjs:60
    XULStore resource://gre/modules/XULStore.sys.mjs:17
```

**Comment by ahubmann** [comment]
Ok, none of the errors point to ThreadVis ... hm. I've had one other report of ThreadVis not working after a restart of Thunderbird unless the add-on is disabled and re-enabled in the add-on manager. Out of curiosity: can you try that?

Anyways, I meant to create a debug-build to troubleshoot this issue, yours sounds familiar enough to warrant some more time invested. I'll try to come up with a version with extensive logging during startup/registration and notifications on selected messages, that will hopefully help. I'll drop a build into this thread (hopefully) sometime next week.

**Comment by ahubmann** [comment]
Ok, let's try to find the culprit. Attached is a debug build that should spam your error console with quite a few log messages, hopefully shedding some light as to why it's not working for you. (GitHub doesn't allow attaching an `.xpi` file, so please rename accordingly.)

[ThreadVis-3.5.2-testing.cffe598.1712338049.zip](https://github.com/threadvis/ThreadVis/files/14888603/ThreadVis-3.5.2-testing.cffe598.1712338049.zip)

If you find the time, please post the output of the error console both for a) installing/activating this version and b) selecting some messages in the message list.

Many thanks!

**Comment by ahubmann** [comment]
Many thanks!

If you hover over the status bar icon, you should see a message similar to this one:
<img width="397" alt="Bildschirmfoto 2024-05-14 um 13 23 08" src="https://github.com/threadvis/ThreadVis/assets/5640706/f502f027-ae5e-4ba9-9264-419dac329a85">

ThreadVis builds upon the global message database Thunderbird maintains, see
<img width="437" alt="Bildschirmfoto 2024-05-14 um 13 24 36" src="https://github.com/threadvis/ThreadVis/assets/5640706/fd58ea89-449c-40f1-866c-6d7d4c2a7eae">

at the very bottom in _Settings->General_. Without the global index, ThreadVis can't enumerate the messages in a thread.

I should probably display this message more prominently.

**Comment by moedn** [comment]
Aww man :facepalm: yes, the Global Search and Indexer was deactivated, I've flipped the switch.

However, now I'm getting ↓

![image](https://github.com/threadvis/ThreadVis/assets/45949491/726f273d-0f5d-4911-b580-239df08b146d)

I've restarted TB already. Maybe the index will update eventually, otherwise it looks like a TB bug…

**Comment by moedn** [comment]
It works now! :tada: It was really just the Indexer. Thousand thanks for your help! :heart:
