### ISSUE TITLE
Not TB 128 compatible

### ISSUE THREAD

**Issue by tinokorth** [threadvis/ThreadVis#59]
Hello,

the Add-On is not compatible with the actual version 128 of Thunderbird.
It needs to be updates.

BR, Tino

**Comment by toddz262** [comment]
TB 128 compatibility is being discussed in another thread: https://github.com/threadvis/ThreadVis/issues/58

**Comment by ahubmann** [comment]
See https://github.com/threadvis/ThreadVis/issues/58#issuecomment-2308814422, getting there...

**Comment by ahubmann** [comment]
Released [3.6.0](https://github.com/threadvis/ThreadVis/releases/tag/3.6.0). Should hopefully be available via Thunderbird Add-Ons and auto-updates soon as well.
